version: '3.8'

services:
  http-client:
    image: jetbrains/intellij-http-client
    volumes:
      - ./docs/api-testing:/workdir
    working_dir: /workdir
    command: >
      --env=dev
      --env-file=http-client.env.json
      api-test.http
